version: '3.9'
services:
  dl:
    image: mongo
    env_file:
      - .mongo.env
    #   reduce logging and set memory to 500mb
    command: --quiet --wiredTigerCacheSizeGB 0.5
    restart: on-failure
    logging:
      driver: local
    volumes:
      - mongodata:/data
    networks:
      - lakenet
    ports:
      - "27017:27017"

  ingester:
    build: 'ingester'
    depends_on: [ dl ]
    restart: on-failure
    volumes:
      - BulkFiles:/BulkFiles
    networks:
      - lakenet
    env_file:
      - .mongo.env
      - .api.env
      - .psql.env

  # arango:
  #   image: arangodb
  #   volumes:
  #     - arangodata:/var/lib/arangodb3
  #   env_file:
  #     - .arango.env
  #   networks:
  #     - arangonet
  #  Enable port sharing to access the web console from a remote browser
  #    ports:
  #      - "8529:8529"
  # graph:
  #   build: 'graph'
  #   depends_on: [ arango ]
  #   networks:
  #     - lakenet
  #     - arangonet
  #   env_file:
  #     - .arango.env
  #     - .mongo.env
  #   logging:
  #     driver: local
  #
  # sql:
  #   build: 'psql'
  #   restart: on-failure
  #   ports:
  #     - "5432:5432"
  #   env_file:
  #     - .psql.env
  #   volumes:
  #     - psqldata:/var/lib/postgresql/data
  #   # need to copy sql schema to init db area
  #   networks:
  #     - psqlnet

volumes:
  BulkFiles:
  mongodata:
  arangodata:
  psqldata:

networks:
  lakenet:
    driver: "bridge"
  arangonet:
    driver: "bridge"
  psqlnet:
    driver: "bridge"
