version: '3.9'
services:
  dl:
    image: mongo
    env_file:
      - .mongo.env
    #   reduce logging and set memory to 500mb
    command: --quiet --wiredTigerCacheSizeGB 0.5
    restart: always
    logging:
      driver: local
    volumes:
      - mongodata:/data
    networks:
      - lakenet

  ingester:
    build: 'ingester'
    depends_on: [ dl ]
    restart: on-failure
    volumes:
      - BulkFiles:/BulkFiles
    networks:
      - lakenet
    env_file:
      - .mongo.env
      - .api.env
      - .psql.env

  arango:
    image: arangodb
    volumes:
      - arangodata:/var/lib/arangodb3
    env_file:
      - .arango.env
    networks:
      - arangonet
  #  Enable port sharing to access the web console from a remote browser
  #    ports:
  #      - "8529:8529"
  graph:
    build: 'graph'
    depends_on: [ arango ]
    networks:
      - lakenet
      - arangonet
    env_file:
      - .arango.env


volumes:
  BulkFiles:
  mongodata:
  arangodata:


networks:
  lakenet:
    driver: "bridge"
  arangonet:
    driver: "bridge"