version: '3.9'
services:
  dl:
    image: mongo
    env_file:
      - .mongo.env
    #   reduce logging and set memory to 500mb
    command: --quiet --wiredTigerCacheSizeGB 0.5
    restart: always
    logging:
      driver: local
    volumes:
      - mongodata:/data
    networks:
      - lakenet

  ingester:
    build: 'ingester'
    depends_on: [ dl ]
    restart: on-failure
    volumes:
      - BulkFiles:/BulkFiles
    networks:
      - lakenet
    env_file:
      - .mongo.env
      - .api.env

volumes:
  BulkFiles:
  mongodata:


networks:
  lakenet:
    driver: "bridge"